name: flow
version: 1.0.0+1
publish_to: none
description: A Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  intl: ^0.17.0
  mime: ^1.0.0
  open_file: ^3.2.1
  uuid: ^3.0.4
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9
  sqflite: ^2.0.0+4
  flutter_local_notifications: ^8.1.1+1
  protobuf: ^2.0.0
  get_it: ^7.2.0
  cached_network_image: ^3.1.0
  geolocator: ^7.4.1
  path_provider: ^2.0.2
  share: ^2.0.4
  just_audio: ^0.9.7
  video_player: ^2.1.14
  get: ^4.3.5
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.3
  file_picker: ^4.0.0
  image_picker: ^0.8.3+2
  webview_flutter: ^2.0.12
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  timeline_tile: ^2.0.0
  charts_flutter: ^0.11.0
  flutter_html: ^2.1.1
  getwidget: ^2.0.3
  flutter: 
    sdk: flutter
  flutter_chat_ui: 
    git: git@github.com:tsundata/flutter_chat_ui.git
  flutter_chat_types: 
    git: git@github.com:tsundata/flutter_chat_types.git

dev_dependencies: 
  json_serializable: ^4.1.4
  build_runner: ^2.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - messages.json
  uses-material-design: true

