name: Dev

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'

    - run: npm install
    
    - run: xcode-select -p

    - run: pod install
      working-directory: ios
      name: Install pod dependencies

    - name: Build iOS (debug)
      run: npx react-native run-ios
